pages = [{"l":"index.html","n":"little-time","t":"little-time","d":"","k":"static"},
{"l":"little/time.html","n":"little.time","t":"package little.time","d":"little/time","k":"package"},
{"l":"little/time.html","n":"DurationMethods","t":"def DurationMethods(duration: Duration): DurationMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"InstantMethods","t":"def InstantMethods(instant: Instant): InstantMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"LocalDateMethods","t":"def LocalDateMethods(date: LocalDate): LocalDateMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"LocalDateTimeMethods","t":"def LocalDateTimeMethods(dateTime: LocalDateTime): LocalDateTimeMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"LocalTimeMethods","t":"def LocalTimeMethods(time: LocalTime): LocalTimeMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"PeriodMethods","t":"def PeriodMethods(period: Period): PeriodMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"TimeStringMethods","t":"def TimeStringMethods(string: String): TimeStringMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"YearMonthMethods","t":"def YearMonthMethods(month: YearMonth): YearMonthMethods","d":"little/time","k":"def"},
{"l":"little/time.html","n":"durationOrdering","t":"given durationOrdering: Ordering[Duration]","d":"little/time","k":"given"},
{"l":"little/time.html","n":"instantOrdering","t":"given instantOrdering: Ordering[Instant]","d":"little/time","k":"given"},
{"l":"little/time.html","n":"localDateOrdering","t":"given localDateOrdering: Ordering[LocalDate]","d":"little/time","k":"given"},
{"l":"little/time.html","n":"localDateTimeOrdering","t":"given localDateTimeOrdering: Ordering[LocalDateTime]","d":"little/time","k":"given"},
{"l":"little/time.html","n":"localTimeOrdering","t":"given localTimeOrdering: Ordering[LocalTime]","d":"little/time","k":"given"},
{"l":"little/time.html","n":"yearMonthOrdering","t":"given yearMonthOrdering: Ordering[YearMonth]","d":"little/time","k":"given"},
{"l":"little/time/CronSchedule.html","n":"CronSchedule","t":"trait CronSchedule extends Schedule","d":"little/time/CronSchedule","k":"trait"},
{"l":"little/time/CronSchedule.html","n":"daysOfMonth","t":"def daysOfMonth: Seq[Int]","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"daysOfWeek","t":"def daysOfWeek: Seq[DayOfWeek]","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"months","t":"def months: Seq[Month]","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"times","t":"def times: Seq[LocalTime]","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withDaysOfMonth","t":"def withDaysOfMonth(days: Seq[Int]): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withDaysOfMonth","t":"def withDaysOfMonth(one: Int, more: Int*): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withDaysOfWeek","t":"def withDaysOfWeek(days: Seq[DayOfWeek]): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withDaysOfWeek","t":"def withDaysOfWeek(one: DayOfWeek, more: DayOfWeek*): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withMonths","t":"def withMonths(months: Seq[Month]): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withMonths","t":"def withMonths(one: Month, more: Month*): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withTimes","t":"def withTimes(times: Seq[LocalTime]): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule.html","n":"withTimes","t":"def withTimes(one: LocalTime, more: LocalTime*): CronSchedule","d":"little/time/CronSchedule","k":"def"},
{"l":"little/time/CronSchedule$.html","n":"CronSchedule","t":"object CronSchedule","d":"little/time/CronSchedule$","k":"object"},
{"l":"little/time/CronSchedule$.html","n":"apply","t":"def apply(times: Seq[LocalTime], daysOfMonth: Seq[Int], months: Seq[Month], daysOfWeek: Seq[DayOfWeek]): CronSchedule","d":"little/time/CronSchedule$","k":"def"},
{"l":"little/time/CronSchedule$.html","n":"apply","t":"def apply(fields: String): CronSchedule","d":"little/time/CronSchedule$","k":"def"},
{"l":"little/time/DurationMethods.html","n":"DurationMethods","t":"class DurationMethods(duration: Duration) extends AnyVal","d":"little/time/DurationMethods","k":"class"},
{"l":"little/time/DurationMethods.html","n":"*","t":"def *(n: Long): Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"+","t":"def +(amount: Duration): Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"-","t":"def -(amount: Duration): Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"/","t":"def /(n: Long): Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"iterateTo","t":"def iterateTo(end: Duration, step: Duration): Iterator[Duration]","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"iterateUntil","t":"def iterateUntil(end: Duration, step: Duration): Iterator[Duration]","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"max","t":"def max(other: Duration): Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"min","t":"def min(other: Duration): Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/DurationMethods.html","n":"unary_-","t":"def unary_-: Duration","d":"little/time/DurationMethods","k":"def"},
{"l":"little/time/InstantMethods.html","n":"InstantMethods","t":"class InstantMethods(instant: Instant) extends AnyVal","d":"little/time/InstantMethods","k":"class"},
{"l":"little/time/InstantMethods.html","n":"+","t":"def +(amount: TemporalAmount): Instant","d":"little/time/InstantMethods","k":"def"},
{"l":"little/time/InstantMethods.html","n":"-","t":"def -(amount: TemporalAmount): Instant","d":"little/time/InstantMethods","k":"def"},
{"l":"little/time/InstantMethods.html","n":"max","t":"def max(other: Instant): Instant","d":"little/time/InstantMethods","k":"def"},
{"l":"little/time/InstantMethods.html","n":"min","t":"def min(other: Instant): Instant","d":"little/time/InstantMethods","k":"def"},
{"l":"little/time/InstantMethods.html","n":"toLocalDateTime","t":"def toLocalDateTime(zone: ZoneId): LocalDateTime","d":"little/time/InstantMethods","k":"def"},
{"l":"little/time/InstantMethods.html","n":"toLocalDateTime","t":"def toLocalDateTime(zone: String): LocalDateTime","d":"little/time/InstantMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"LocalDateMethods","t":"class LocalDateMethods(date: LocalDate) extends AnyVal","d":"little/time/LocalDateMethods","k":"class"},
{"l":"little/time/LocalDateMethods.html","n":"+","t":"def +(days: Long): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"+","t":"def +(amount: TemporalAmount): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"-","t":"def -(days: Long): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"-","t":"def -(amount: TemporalAmount): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atEndOfMonth","t":"def atEndOfMonth: LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atEndOfWeek","t":"def atEndOfWeek: LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atEndOfWeek","t":"def atEndOfWeek(lastDay: DayOfWeek): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atEndOfYear","t":"def atEndOfYear: LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atStartOfMonth","t":"def atStartOfMonth: LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atStartOfWeek","t":"def atStartOfWeek: LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atStartOfWeek","t":"def atStartOfWeek(firstDay: DayOfWeek): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"atStartOfYear","t":"def atStartOfYear: LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"iterateTo","t":"def iterateTo(end: LocalDate, step: Period): Iterator[LocalDate]","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"iterateUntil","t":"def iterateUntil(end: LocalDate, step: Period): Iterator[LocalDate]","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"max","t":"def max(other: LocalDate): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"min","t":"def min(other: LocalDate): LocalDate","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateMethods.html","n":"toYearMonth","t":"def toYearMonth: YearMonth","d":"little/time/LocalDateMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"LocalDateTimeMethods","t":"class LocalDateTimeMethods(dateTime: LocalDateTime) extends AnyVal","d":"little/time/LocalDateTimeMethods","k":"class"},
{"l":"little/time/LocalDateTimeMethods.html","n":"+","t":"def +(amount: TemporalAmount): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"-","t":"def -(amount: TemporalAmount): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfDay","t":"def atEndOfDay(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfHour","t":"def atEndOfHour(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfMicros","t":"def atEndOfMicros(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfMillis","t":"def atEndOfMillis(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfMinute","t":"def atEndOfMinute(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfMonth","t":"def atEndOfMonth(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfSecond","t":"def atEndOfSecond(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfWeek","t":"def atEndOfWeek(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfWeek","t":"def atEndOfWeek(lastDay: DayOfWeek)(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atEndOfYear","t":"def atEndOfYear(using precision: TimePrecision): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfDay","t":"def atStartOfDay: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfHour","t":"def atStartOfHour: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfMicros","t":"def atStartOfMicros: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfMillis","t":"def atStartOfMillis: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfMinute","t":"def atStartOfMinute: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfMonth","t":"def atStartOfMonth: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfSecond","t":"def atStartOfSecond: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfWeek","t":"def atStartOfWeek: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfWeek","t":"def atStartOfWeek(firstDay: DayOfWeek): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"atStartOfYear","t":"def atStartOfYear: LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"iterateTo","t":"def iterateTo(end: LocalDateTime, step: TemporalAmount): Iterator[LocalDateTime]","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"iterateUntil","t":"def iterateUntil(end: LocalDateTime, step: TemporalAmount): Iterator[LocalDateTime]","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"max","t":"def max(other: LocalDateTime): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"min","t":"def min(other: LocalDateTime): LocalDateTime","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"toInstant","t":"def toInstant(zone: ZoneId): Instant","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"toInstant","t":"def toInstant(zone: String): Instant","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalDateTimeMethods.html","n":"toYearMonth","t":"def toYearMonth: YearMonth","d":"little/time/LocalDateTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"LocalTimeMethods","t":"class LocalTimeMethods(time: LocalTime) extends AnyVal","d":"little/time/LocalTimeMethods","k":"class"},
{"l":"little/time/LocalTimeMethods.html","n":"+","t":"def +(amount: TemporalAmount): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"-","t":"def -(amount: TemporalAmount): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atEndOfDay","t":"def atEndOfDay(using precision: TimePrecision): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atEndOfHour","t":"def atEndOfHour(using precision: TimePrecision): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atEndOfMicros","t":"def atEndOfMicros(using precision: TimePrecision): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atEndOfMillis","t":"def atEndOfMillis(using precision: TimePrecision): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atEndOfMinute","t":"def atEndOfMinute(using precision: TimePrecision): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atEndOfSecond","t":"def atEndOfSecond(using precision: TimePrecision): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atStartOfDay","t":"def atStartOfDay: LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atStartOfHour","t":"def atStartOfHour: LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atStartOfMicros","t":"def atStartOfMicros: LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atStartOfMillis","t":"def atStartOfMillis: LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atStartOfMinute","t":"def atStartOfMinute: LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"atStartOfSecond","t":"def atStartOfSecond: LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"iterateTo","t":"def iterateTo(end: LocalTime, step: Duration): Iterator[LocalTime]","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"iterateUntil","t":"def iterateUntil(end: LocalTime, step: Duration): Iterator[LocalTime]","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"max","t":"def max(other: LocalTime): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/LocalTimeMethods.html","n":"min","t":"def min(other: LocalTime): LocalTime","d":"little/time/LocalTimeMethods","k":"def"},
{"l":"little/time/PeriodMethods.html","n":"PeriodMethods","t":"class PeriodMethods(period: Period) extends AnyVal","d":"little/time/PeriodMethods","k":"class"},
{"l":"little/time/PeriodMethods.html","n":"*","t":"def *(n: Int): Period","d":"little/time/PeriodMethods","k":"def"},
{"l":"little/time/PeriodMethods.html","n":"+","t":"def +(amount: Period): Period","d":"little/time/PeriodMethods","k":"def"},
{"l":"little/time/PeriodMethods.html","n":"-","t":"def -(amount: Period): Period","d":"little/time/PeriodMethods","k":"def"},
{"l":"little/time/PeriodMethods.html","n":"unary_-","t":"def unary_-: Period","d":"little/time/PeriodMethods","k":"def"},
{"l":"little/time/Schedule.html","n":"Schedule","t":"trait Schedule","d":"little/time/Schedule","k":"trait"},
{"l":"little/time/Schedule.html","n":"+","t":"def +(time: LocalDateTime): Schedule","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule.html","n":"++","t":"def ++(other: Schedule): Schedule","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule.html","n":"add","t":"def add(time: LocalDateTime): Schedule","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule.html","n":"between","t":"def between(start: LocalDateTime, end: LocalDateTime): Iterator[LocalDateTime]","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule.html","n":"between","t":"def between(start: LocalDate, end: LocalDate): Iterator[LocalDateTime]","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule.html","n":"combine","t":"def combine(other: Schedule): Schedule","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule.html","n":"next","t":"def next(after: LocalDateTime): Option[LocalDateTime]","d":"little/time/Schedule","k":"def"},
{"l":"little/time/Schedule$.html","n":"Schedule","t":"object Schedule","d":"little/time/Schedule$","k":"object"},
{"l":"little/time/Schedule$.html","n":"apply","t":"def apply(times: Seq[LocalDateTime]): Schedule","d":"little/time/Schedule$","k":"def"},
{"l":"little/time/Schedule$.html","n":"apply","t":"def apply(one: LocalDateTime, more: LocalDateTime*): Schedule","d":"little/time/Schedule$","k":"def"},
{"l":"little/time/TimePrecision.html","n":"TimePrecision","t":"trait TimePrecision extends Ordered[TimePrecision]","d":"little/time/TimePrecision","k":"trait"},
{"l":"little/time/TimePrecision.html","n":"compare","t":"def compare(that: TimePrecision): Int","d":"little/time/TimePrecision","k":"def"},
{"l":"little/time/TimePrecision.html","n":"limit","t":"def limit: LocalTime","d":"little/time/TimePrecision","k":"def"},
{"l":"little/time/TimePrecision$.html","n":"TimePrecision","t":"object TimePrecision","d":"little/time/TimePrecision$","k":"object"},
{"l":"little/time/TimePrecision$$FractionalSeconds$.html","n":"FractionalSeconds","t":"object FractionalSeconds","d":"little/time/TimePrecision$$FractionalSeconds$","k":"object"},
{"l":"little/time/TimePrecision$$FractionalSeconds$.html","n":"apply","t":"def apply(scale: Int): FractionalSeconds","d":"little/time/TimePrecision$$FractionalSeconds$","k":"def"},
{"l":"little/time/TimePrecision$$FractionalSeconds$.html","n":"unapply","t":"def unapply(fsecs: FractionalSeconds): Option[Int]","d":"little/time/TimePrecision$$FractionalSeconds$","k":"def"},
{"l":"little/time/TimePrecision$$FractionalSeconds.html","n":"FractionalSeconds","t":"trait FractionalSeconds extends TimePrecision","d":"little/time/TimePrecision$$FractionalSeconds","k":"trait"},
{"l":"little/time/TimePrecision$$FractionalSeconds.html","n":"limit","t":"val limit: LocalTime","d":"little/time/TimePrecision$$FractionalSeconds","k":"val"},
{"l":"little/time/TimePrecision$$FractionalSeconds.html","n":"scale","t":"def scale: Int","d":"little/time/TimePrecision$$FractionalSeconds","k":"def"},
{"l":"little/time/TimePrecision$$Hours$.html","n":"Hours","t":"object Hours extends TimePrecision","d":"little/time/TimePrecision$$Hours$","k":"object"},
{"l":"little/time/TimePrecision$$Hours$.html","n":"limit","t":"val limit: LocalTime","d":"little/time/TimePrecision$$Hours$","k":"val"},
{"l":"little/time/TimePrecision$$Microseconds$.html","n":"Microseconds","t":"object Microseconds extends FractionalSeconds","d":"little/time/TimePrecision$$Microseconds$","k":"object"},
{"l":"little/time/TimePrecision$$Microseconds$.html","n":"scale","t":"val scale: Int","d":"little/time/TimePrecision$$Microseconds$","k":"val"},
{"l":"little/time/TimePrecision$$Milliseconds$.html","n":"Milliseconds","t":"object Milliseconds extends FractionalSeconds","d":"little/time/TimePrecision$$Milliseconds$","k":"object"},
{"l":"little/time/TimePrecision$$Milliseconds$.html","n":"scale","t":"val scale: Int","d":"little/time/TimePrecision$$Milliseconds$","k":"val"},
{"l":"little/time/TimePrecision$$Minutes$.html","n":"Minutes","t":"object Minutes extends TimePrecision","d":"little/time/TimePrecision$$Minutes$","k":"object"},
{"l":"little/time/TimePrecision$$Minutes$.html","n":"limit","t":"val limit: LocalTime","d":"little/time/TimePrecision$$Minutes$","k":"val"},
{"l":"little/time/TimePrecision$$Nanoseconds$.html","n":"Nanoseconds","t":"object Nanoseconds extends FractionalSeconds","d":"little/time/TimePrecision$$Nanoseconds$","k":"object"},
{"l":"little/time/TimePrecision$$Nanoseconds$.html","n":"scale","t":"val scale: Int","d":"little/time/TimePrecision$$Nanoseconds$","k":"val"},
{"l":"little/time/TimePrecision$$Seconds$.html","n":"Seconds","t":"object Seconds extends TimePrecision","d":"little/time/TimePrecision$$Seconds$","k":"object"},
{"l":"little/time/TimePrecision$$Seconds$.html","n":"limit","t":"val limit: LocalTime","d":"little/time/TimePrecision$$Seconds$","k":"val"},
{"l":"little/time/TimeStringMethods.html","n":"TimeStringMethods","t":"class TimeStringMethods(string: String) extends AnyVal","d":"little/time/TimeStringMethods","k":"class"},
{"l":"little/time/TimeStringMethods.html","n":"toDuration","t":"def toDuration: Duration","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/TimeStringMethods.html","n":"toInstant","t":"def toInstant: Instant","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/TimeStringMethods.html","n":"toLocalDate","t":"def toLocalDate: LocalDate","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/TimeStringMethods.html","n":"toLocalDateTime","t":"def toLocalDateTime: LocalDateTime","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/TimeStringMethods.html","n":"toLocalTime","t":"def toLocalTime: LocalTime","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/TimeStringMethods.html","n":"toPeriod","t":"def toPeriod: Period","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/TimeStringMethods.html","n":"toYearMonth","t":"def toYearMonth: YearMonth","d":"little/time/TimeStringMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"YearMonthMethods","t":"class YearMonthMethods(month: YearMonth) extends AnyVal","d":"little/time/YearMonthMethods","k":"class"},
{"l":"little/time/YearMonthMethods.html","n":"+","t":"def +(months: Long): YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"+","t":"def +(amount: TemporalAmount): YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"-","t":"def -(months: Long): YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"-","t":"def -(amount: TemporalAmount): YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"atEndOfYear","t":"def atEndOfYear: YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"atStartOfYear","t":"def atStartOfYear: YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"iterateTo","t":"def iterateTo(end: YearMonth, step: Period): Iterator[YearMonth]","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"iterateUntil","t":"def iterateUntil(end: YearMonth, step: Period): Iterator[YearMonth]","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"max","t":"def max(other: YearMonth): YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"little/time/YearMonthMethods.html","n":"min","t":"def min(other: YearMonth): YearMonth","d":"little/time/YearMonthMethods","k":"def"},
{"l":"docs/index.html","n":"little-time","t":"little-time","d":"","k":"static"}];